// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRRqpTp1gW0Y9bKMMdOO42S1figO-226g',
    appId: '1:1348324644:web:25bfdaa9f4993d0d4a77b1',
    messagingSenderId: '1348324644',
    projectId: 'saarthi-c3cf4',
    authDomain: 'saarthi-c3cf4.firebaseapp.com',
    storageBucket: 'saarthi-c3cf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiLWhMFf-we2MAKBh4QCB8tTay10VaE2w',
    appId: '1:1348324644:android:2dd8183d4ab7f0104a77b1',
    messagingSenderId: '1348324644',
    projectId: 'saarthi-c3cf4',
    storageBucket: 'saarthi-c3cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmrd8uz97ZKRM5gtNRno3mzSTJuPrEQM',
    appId: '1:1348324644:ios:8118d4f3cce419664a77b1',
    messagingSenderId: '1348324644',
    projectId: 'saarthi-c3cf4',
    storageBucket: 'saarthi-c3cf4.firebasestorage.app',
    iosClientId: '1348324644-vd0mdtgm1vo7ct6piv69n5jl3k0or8mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmrd8uz97ZKRM5gtNRno3mzSTJuPrEQM',
    appId: '1:1348324644:ios:8118d4f3cce419664a77b1',
    messagingSenderId: '1348324644',
    projectId: 'saarthi-c3cf4',
    storageBucket: 'saarthi-c3cf4.firebasestorage.app',
    iosClientId: '1348324644-vd0mdtgm1vo7ct6piv69n5jl3k0or8mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRRqpTp1gW0Y9bKMMdOO42S1figO-226g',
    appId: '1:1348324644:web:37c2926fa596065c4a77b1',
    messagingSenderId: '1348324644',
    projectId: 'saarthi-c3cf4',
    authDomain: 'saarthi-c3cf4.firebaseapp.com',
    storageBucket: 'saarthi-c3cf4.firebasestorage.app',
  );
}
